package com.system.po;

import java.io.Serializable;

public class SysDictType implements Serializable {
    /**
     * 字典类型
     *
     * @mbggenerated 2016-02-25 09:37:11
     */
    private String dictType;

    /**
     * 字典类型描述
     *
     * @mbggenerated 2016-02-25 09:37:11
     */
    private String dictDesc;

    /**
     * 备注
     *
     * @mbggenerated 2016-02-25 09:37:11
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict_type
     *
     * @mbggenerated 2016-02-25 09:37:11
     */
    private static final long serialVersionUID = 1L;

    /**
     * 字典类型
     *
     * @mbggenerated 2016-02-25 09:37:11
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * 字典类型
     *
     * @param dictType java.lang.String
     *
     * @mbggenerated 2016-02-25 09:37:11
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * 字典类型描述
     *
     * @mbggenerated 2016-02-25 09:37:11
     */
    public String getDictDesc() {
        return dictDesc;
    }

    /**
     * 字典类型描述
     *
     * @param dictDesc java.lang.String
     *
     * @mbggenerated 2016-02-25 09:37:11
     */
    public void setDictDesc(String dictDesc) {
        this.dictDesc = dictDesc == null ? null : dictDesc.trim();
    }

    /**
     * 备注
     *
     * @mbggenerated 2016-02-25 09:37:11
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @param remark java.lang.String
     *
     * @mbggenerated 2016-02-25 09:37:11
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}